version: "3.8"

services:
  server:
    build:
      context: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000

  client:
    build:
      context: ./web-client
    ports:
      - "5173:5173"
    environment:
      - PORT=5173
    depends_on:
      - server
    volumes:
      - ./web-client:/app
      - /app/node_modules
    # command: ["npm", "run", "dev"]]
